version: "3.9"

services:

  minilisp-scratchpad:
    image: ${IMG}
    container_name: ${SCRATCHPADER}
    ports:
      - ${SCRATCHPAD_PORT}:${SCRATCHPAD_PORT}
    command: serve -s -l ${SCRATCHPAD_PORT} 4-scratchpad/dist

  minilisp-http:
    image: ${IMG}
    container_name: ${LISP_HTTPER}
    ports:
      - ${LISP_HTTP_PORT}:${LISP_HTTP_PORT}
    command: runhaskell 3-HTTP/HTTP.hs

  nginx-service:
    image: ${NGINX_IMG}
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/5-docker/Dockerfile-nginx
    container_name: nginx-service
    ports:
      - "80:80"
    #volumes:
      # - web-root:/var/www/html
      # - ${PWD}/../6-web-publish/nginx-conf.d:/etc/nginx/conf.d
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
